INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8000,'Albums');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8001,'Artf. Flowers');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8002,'Bath Items');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8003,'Bedding');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8004,'Books');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8005,'China ');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8006,'Xmas Items');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8007,'Closet Items');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8008,'Clothes');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8009,'Dishes');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8010,'Food');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8011,'Glass');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8012,'Glassware');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8013,'Knickknacks');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8014,'Lam');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8015,'Lamp Shade');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8016,'Linen');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8017,'Mirror');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8018,'Picture');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8019,'Pots & Pans');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8020,'Shoes');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8021,'Tools');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8022,'Answering Machine');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8023,'Aquarium');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8024,'Artificial Plant');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8025,'Bags');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8026,'Basket');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8027,'Bean Bag');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8028,'Beauty Aids');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8029,'Belts');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8030,'Billiard Supplies');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8031,'Bird Cage');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8033,'Boots');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8034,'Bowling Ball');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8035,'Bucket');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8036,'Calendar');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8037,'Camera');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8038,'Candles');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8039,'Canisters');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8040,'Canned Food');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8041,'Car Supplies');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8042,'Cassettes');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8043,'Cassette Player');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8044,'Chandelier');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8045,'Children''s Books');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8046,'Christmas Items');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8047,'Cleaning Supplies');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8048,'Clock');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8049,'Clothes');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8050,'Clothes (Hers)');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8051,'Clothes (His)');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8052,'Coats');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8053,'Coffee Maker');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8054,'Compact Discs');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8055,'CD Player');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8056,'Computer');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8057,'Computer Manuals');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8058,'Cooking Oils');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8059,'Cookbooks');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8060,'Craft Items');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8061,'Crystal');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8062,'Cups');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8063,'Curling Iron');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8064,'Curtains');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8065,'Cushions');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8066,'Cutting Board');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8067,'Desk Items');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8068,'Detergents/Soaps');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8069,'Dishes');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8070,'Dish Towels');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8071,'Dresser Mirror');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8072,'Dried Flowers');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8073,'Dry Food');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8074,'Easter Items');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8075,'Encyclopedias');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8076,'Extension cord');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8077,'Fan');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8078,'Figurine');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8079,'Files');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8080,'Fireplace Tools');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8081,'Fishing Poles');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8082,'Flash Lights');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8083,'Floor Lamp');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8084,'Flower Pots');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8085,'Food ');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8086,'Framed Art');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8087,'Games');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8088,'Garden Tools');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8089,'Gift Wrap');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8090,'Glass');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8091,'Glassware');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8092,'Glass Shelf');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8093,'Glass Table Top');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8094,'Globe');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8095,'Gloves');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8096,'Golf Bag');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8097,'Golf Clubs');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8098,'Gun');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8099,'Hair Dryer');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8100,'Halloween Items');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8101,'Hand Tools');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8102,'Hangers');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8103,'Hats');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8104,'Health Aids');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8105,'Helmet');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8106,'Hummel');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8107,'Iron');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8108,'Jars');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8109,'Jewelry');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8110,'Jewelry Box');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8111,'Keyboard');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8112,'Knives');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8113,'Lawn Items');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8114,'Lights');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8115,'Linens');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8116,'Liquor');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8117,'Live Plant');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8118,'Llardro');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8119,'Luggage');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8120,'Magazines');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8121,'Marble');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8122,'Microwave');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8123,'Monitor');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8124,'Mugs');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8125,'Notebook/Binders');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8126,'Painting');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8127,'Painting Supplies');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8128,'Pans');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8129,'Papers');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8130,'Pet Items');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8131,'Phone');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8132,'Photos');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8133,'Pillows');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8134,'Place Mats');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8135,'Plaques');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8136,'Plastic Wrap');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8137,'Platters');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8138,'Posters');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8139,'Power Tools');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8140,'Precious Moments');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8141,'Printer');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8142,'Punch Bowl');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8143,'Purses');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8144,'Racquets');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8145,'Radio');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8146,'Remote');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8147,'Rug');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8148,'Scale');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8149,'Sculpture');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8150,'Sewing Machine');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8151,'Shoes');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8152,'Shower Curtain');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8153,'Silver');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8154,'Silverware');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8155,'Sleeping Bag');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8156,'Small Appliances');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8157,'Speaker');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8158,'Spices');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8159,'Sports Equipment');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8160,'Stationary');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8161,'Statue');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8162,'Stemware');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8163,'Stereo');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8164,'Stuffed Animals');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8165,'Sweaters');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8166,'Sweatshirts');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8167,'Table Linens');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8168,'Tackle Box');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8169,'Tall Items');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8170,'Tarps');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8171,'Tea Pot');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8172,'Television');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8173,'Ties');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8174,'Toiletries');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8175,'Toys');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8176,'Tupperware');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8177,'Tuner');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8178,'Turntable');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8179,'Typewriter');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8180,'Umbrella');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8181,'Utensils');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8182,'Vase');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8183,'VCR');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8184,'Video Games');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8185,'Video Tapes');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8186,'Wok');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8187,'Wreath');
INSERT INTO PVOCartonContents(CartonContentID, ContentDescription) VALUES(8188,'Yard Tools');
