//
//  PVONavigationListItem.h
//  Survey
//
//  Created by Tony Brame on 7/7/11.
//  Copyright 2011 __MyCompanyName__. All rights reserved.
//

#import <Foundation/Foundation.h>

//org 1
#define PVO_ENTER_TARE_WEIGHT 1
#define PVO_CONFIRM_VALUATION 2
#define PVO_CONFIRM_LOAD_DATE 3
#define PVO_INVENTORY 4
#define PVO_ORIGIN_SERVICES 5

//org 2
#define PVO_GENERAL_COMMENTS 6
#define PVO_PAYMENT_METHOD 7
#define PVO_ORG_PROPERTY_DAMAGE 8
#define PVO_P_EX_PU_INV 9
#define PVO_P_INV_CARTON_DETAIL 10

//org 3
#define PVO_P_COST_DETAIL 11
#define PVO_P_BOL_TERMS 12
#define PVO_P_GYPSY_MOTH 13
#define PVO_ORG_COMPLETE 14

//in route
#define PVO_GROSS_WEIGHT 15
#define PVO_OA_CHARGES 16
#define PVO_RATE_SHIPMENT 17
#define PVO_SEND_INV_SERVICES 18
#define PVO_IN_ROUTE_COMPLETE 19

//dest 1
#define PVO_REWEIGH 20
#define PVO_DEST_SERVICES 21
#define PVO_RE_RATE 22
#define PVO_CONFIRM_PAYMENT 23
#define PVO_FINAL_DEL_DATE 24
#define PVO_DELIVER_SHIPMENT 25

//dest 2
#define PVO_DEST_PROPERTY_DAMAGE 26
#define PVO_P_EX_DEL 27
#define PVO_P_DEL_EXCP 28
#define PVO_P_BOL 29

//dest 3
#define PVO_SEND_DOCS 30
#define PVO_PROCESS_COMPLETE 31


//added items after initial ACI Items
#define PVO_P_ORG_HIGH_VALUE 32
#define PVO_P_DEL_HIGH_VALUE 33
#define PVO_P_ESIGN_AGREEMENT 34
#define PVO_P_HVI_INSTRUCTIONS 35
#define PVO_P_ROOM_CONDITIONS 36
#define PVO_P_HARDWARE_INVENTORY 37
#define PVO_P_PRIORITY_INVENTORY 38
#define PVO_WEIGHT_TICKET 39
#define PVO_VIEW_BOL 40
#define PVO_P_PACKING_SERVICES 41
#define PVO_P_PACK_PER_INVENTORY 42
#define PVO_UPLOAD_ORG_DOCS 43
#define PVO_UPLOAD_DEST_DOCS 44

#define PVO_ASPOD_ORIGIN_DETAILS 45
#define PVO_P_ASPOD_ORIGIN 46
#define PVO_ASPOD_DESTINATION_DETAILS 47
#define PVO_P_ASPOD_DESTINATION 48

#define PVO_P_DELIVER_ALL_CONFIRM 49

//added a different id for atlas since it loads a different doc, same sig
#define PVO_P_ATLAS_ORG_HIGH_VALUE 50

#define PVO_P_RIDER_EXCEPTIONS 51

#define PVO_ATTACH_DOCUMENT_ORG 52
#define PVO_ATTACH_DOCUMENT_DEST 53

#define PVO_BOL_DETAILS 56
#define PVO_BOL_ORIGIN 57
#define PVO_BOL_SIT 58
#define PVO_BOL_DEST 59

#define PVO_DOV_DETAILS 60
#define PVO_DOV 61

//auto inventory options
#define PVO_AUTO_INVENTORY_ORIG 62
#define PVO_AUTO_INVENTORY_REPORT_ORIG 63
#define PVO_AUTO_INVENTORY_BOL_ORIG 79
#define PVO_AUTO_INVENTORY_DEST 64
#define PVO_AUTO_INVENTORY_REPORT_DEST 65
#define PVO_AUTO_INVENTORY_BOL_DEST 80

#define PVO_BULKY_INVENTORY_ORIG 153
#define PVO_BULKY_INVENTORY_ORIG_REPORT 154
#define PVO_BULKY_INVENTORY_DEST 155
#define PVO_BULKY_INVENTORY_DEST_REPORT 156

#define PVO_BULKY_INVENTORY_REPORT_ORIG 410
#define PVO_BULKY_INVENTORY_REPORT_DEST 411

#define PVO_CREW 500
#define PVO_ACTIONS 501
#define PVO_CHECKLIST 502

//load tag, display text, completed flag, selectable

@interface PVONavigationListItem : NSObject {
    int navItemID;
    int categoryID;
    NSString *display;
    
    //neither of these are currently used in the databases.
    BOOL required;
    
    int reportNoteType;
    int imageDisplayType;
}

@property (nonatomic) int navItemID;
@property (nonatomic) int custID;
@property (nonatomic) BOOL required;
@property (nonatomic, strong) NSString *display;
@property (nonatomic) int reportNoteType;
@property (nonatomic) int imageDisplayType;

@property (nonatomic) int reportTypeID;
@property (nonatomic, strong) NSString *signatureIDs;
@property (nonatomic) int itemCategory;
@property (nonatomic) int enabledOverride; //0 no override, 1 = enabled, -1 = disabled

+(int)reportIDForNavID:(int)navID;
+(NSString*)signatureIDForNavID:(int)navID;

-(BOOL)hasRequiredSignatures;
-(BOOL)getReportWasUploaded:(int)custID;
-(void)setReportWasUploaded:(BOOL)wasUploaded forCustomer:(int)custID;

-(BOOL)completed;
-(BOOL)enabled;
-(BOOL)isReportOption;
-(BOOL)enableUploadFromShipmentMenu;
-(BOOL)hasReportNotes;
-(BOOL)isBulky;

//this was added due to the "View BOL" option in AtlasNet - this report is downloaded from Atlas, not generated by us.
-(BOOL)reportOptionSourcedExternally;
-(int)getPVOChangeDataToCheck;
-(BOOL)hasSignatureType:(int)sigTypeID;
+(BOOL)signatureRequiresTypedFullName:(int)signatureID;

@end
