//
//  PVOSignature.h
//  Survey
//
//  Created by Tony Brame on 9/20/11.
//  Copyright 2011 __MyCompanyName__. All rights reserved.
//

#import <Foundation/Foundation.h>


#define IMG_PVO_DIRECTORY @"/PVOImages/"
#define IMG_PVO_FILE_NAME @"PVO_SIG"

enum PVO_SIGNATURE_TYPE {
    PVO_SIGNATURE_TYPE_DRIVER = 1,
    PVO_SIGNATURE_TYPE_ORG_INVENTORY = 2,
    PVO_SIGNATURE_TYPE_DEST_INVENTORY = 3,
    PVO_SIGNATURE_TYPE_ORG_HIGH_VALUE = 4,
    PVO_SIGNATURE_TYPE_DEST_HIGH_VALUE = 5,
    PVO_SIGNATURE_TYPE_ESIGN_AGREEMENT = 6,
    PVO_SIGNATURE_TYPE_CLAIM = 7,
    PVO_SIGNATURE_TYPE_ROOM_CONDITIONS = 8,
    PVO_SIGNATURE_TYPE_HARDWARE_INVENTORY = 9,
    PVO_SIGNATURE_TYPE_PRIORITY_INVENTORY = 10,
    PVO_SIGNATURE_TYPE_PACKING_SERVICES = 11,
    PVO_SIGNATURE_TYPE_ORIGIN_ASPOD = 12,
    PVO_SIGNATURE_TYPE_DESTINATION_ASPOD = 13,
    PVO_SIGNATURE_TYPE_DELIVER_ALL = 14,
    PVO_SIGNATURE_TYPE_PACKER = 15,
    PVO_SIGNATURE_TYPE_RIDER_EXCEPTIONS = 16,
    PVO_SIGNATURE_TYPE_BOL_ORIGIN = 17,
    PVO_SIGNATURE_TYPE_BOL_SIT = 18,
    PVO_SIGNATURE_TYPE_BOL_DESTINATION = 19,
    PVO_SIGNATURE_TYPE_DOV = 20,
    PVO_SIGNATURE_TYPE_UNPACKING_SERVICES = 21,
    PVO_SIGNATURE_TYPE_BOL_O_MILITARY = 22,
    PVO_SIGNATURE_TYPE_BOL_O_SPECIAL_SERVICES = 23,
    PVO_SIGNATURE_TYPE_BOL_D_SPECIAL_SERVICES = 24,    
    PVO_SIGNATURE_TYPE_DOV_INITIALS = 25,
    PVO_SIGNATURE_TYPE_AUTO_INVENTORY_VEHICLE_ORIG = 26,
    PVO_SIGNATURE_TYPE_AUTO_INVENTORY = 27,
    PVO_SIGNATURE_TYPE_DEST_ROOM_CONDITIONS = 28,
    PVO_SIGNATURE_TYPE_AUTO_INVENTORY_BOL_ORIG = 29,
    PVO_SIGNATURE_TYPE_AUTO_INVENTORY_BOL_DEST = 30,
    PVO_SIGNATURE_TYPE_AUTO_INVENTORY_VEHICLE_DEST = 31,
    PVO_SIGNATURE_TYPE_BULKY_INVENTORY_ORIG = 230,
    PVO_SIGNATURE_TYPE_BULKY_INVENTORY_DEST = 231,
    PVO_SIGNATURE_TYPE_SP_INVENTORY = 375,
    PVO_SIGNATURE_TYPE_SP_INVENTORY_DEST = 376


};

@interface PVOSignature : NSObject{
    int pvoSigID;
    int custID;
    int pvoSigTypeID;
    int referenceID;
    NSString *fileName;
    NSDate *sigDate;
}

@property (nonatomic) int pvoSigID;
@property (nonatomic) int custID;
@property (nonatomic) int pvoSigTypeID;
@property (nonatomic) int referenceID;

@property (nonatomic, strong) NSString *fileName;
@property (nonatomic, strong) NSDate *sigDate;

-(NSString*)fullFilePath;
-(UIImage*)signatureData;

@end
